name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: |
        When I run `slamy channels list --unread`, I get an error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Set `SLACK_USER_TOKEN` environment variable
        2. Run `slamy channels list --unread`
        3. Observe error message
        4. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
      placeholder: Channels with unread messages should be listed
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened (include error messages if any)
      placeholder: |
        Error: failed to list channels: ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Slamy version
      description: Run `slamy --version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: go
    attributes:
      label: Go version
      description: Run `go version`
      placeholder: "go1.25.2 darwin/arm64"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., macOS 15.3, Ubuntu 24.04, Windows 11
      placeholder: "macOS 15.3"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or logs that might help
    validations:
      required: false
