name: Question
description: Ask a question about using Slamy
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know about Slamy?
      placeholder: |
        How do I configure the MCP server with Claude Desktop?
        What Slack token scopes are required?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context or what you've already tried
      placeholder: |
        I've tried... but I'm getting...
        I looked at the documentation but...
    validations:
      required: false
